name: Library unit test
description: Build and test internal Library
inputs:
  working-directory:
    required: true
    description: Which library to build
  check_name:
    required: true
    description: Name which is displayed in test results
  use-cache:
    required: false
    default: 'True'
    description: Enable or disable Conan caching

runs:
    using: 'composite'
    steps:
    - name: Cache Conan packages
      if: inputs.use-cache == 'True'
      uses: actions/cache@v6
      with:
        path: ~/.conan2/p
        key: ${{ runner.os }}-conan2-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/conanfile.txt', inputs.working-directory), format('{0}/conanfile.py', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-conan2-${{ inputs.working-directory }}-

    - name: Conan install
      run: conan install . --build=missing -c tools.cmake.cmaketoolchain:generator="Unix Makefiles" --format=json > graph.json
      working-directory: ${{inputs.working-directory}}
      shell: bash

    - name: Conan upload transient binaries
      # Extract refs where binary is "build" AND the name does not contain "-snapshot"
      # Upload only the filtered stable artifacts
      run: |
        STABLE_BUILT=$(jq -r '.graph.nodes[] | select(.binary == "Build" and (.ref | contains("-snapshot") | not) and .ref != "conanfile") | .ref' graph.json)
        echo "=== Selected refs for Upload ==="
        echo "$STABLE_BUILT"
        for ref in $STABLE_BUILT; do
          if [ -n "$ref" ] && [ "$ref" != "null" ]; then
            conan upload "$ref" -r neboskreb-conan --confirm
          fi
        done
      working-directory: ${{inputs.working-directory}}
      shell: bash

    - name: Conan create
      run: conan create .
      env:
        CONAN_TEST_RESULTS_DIR: ${{ github.workspace }}/test-results
        GTEST_OUTPUT: "xml:${{ github.workspace }}/test-results/"
      working-directory: ${{inputs.working-directory}}
      shell: bash

    - name: Publish Test Report
      # Now collect the results and report the failures, if present
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always() # always run even if the previous step fails
      with:
        files: "xml:${{ github.workspace }}/test-results/"
        check_name: ${{inputs.check_name}}
