name: Conan create upload
description: Build the library with GitHub profile and upload it to Neboskreb remote so it can be pulled for later builds
inputs:
  working-directory:
    required: true
    description: Which library to build

runs:
    using: 'composite'
    steps:
    - name: Detect CMake and Conan scripts
      run: |
        chmod +x ${{github.action_path}}/detect-library.sh
        # Suspend the instant error handling, execute the script, and re-enable the error handling
        set +e
        OUTPUT=$(${{github.action_path}}/detect-library.sh ${{inputs.working-directory}} conanfile-test.py)
        EXIT_CODE=$?
        set -e
        
        # Handle non-zero exit codes (guard clause)
        if [ $EXIT_CODE -ne 0 ]; then
          case $EXIT_CODE in
            1) echo "::error::Working directory not found: ${{inputs.working-directory}}" ;;
            2) echo "::error::Conan file not found." ;;
            3) echo "::error::Command 'conan inspect' failed." ;;
            4) echo "::error::Library name not detected via conan inspect." ;;
            5) echo "::error::Library version not detected via conan inspect." ;;
            *) echo "::error::An unexpected error occurred (Exit code: $EXIT_CODE)." ;;
          esac
          exit $EXIT_CODE
        fi

        echo "$OUTPUT" >> "$GITHUB_ENV"
      shell: bash


    - name: Conan upload to the production repo
      if: ${{env.is_snapshot == 'False'}}
      run: conan upload ${{env.library}} -r neboskreb-conan
      shell: bash

    - name: Conan upload to snapshots repo
      # Also cleanup the intermediate revisions to minimize the space waste
      if: ${{env.is_snapshot == 'True'}}
      run: |
        conan remove "*/*#!latest" -c 
        conan upload ${{env.library}} -r neboskreb-snapshots --force
        conan remove "*/*#!latest" -c -r neboskreb-snapshots
      shell: bash
